### ISSUE TITLE
eight_queens_steepest_descent_optimizer.py

### ISSUE THREAD

**Issue by RavenHex1296** [walliuswilliam/machine-learning#13]
At the last two lines of your eight_queens_steepest_descent_optimizer, you can actually combine the two prints to get print('n =', n, ':', '\n', 'optimized board', steepest_descent_optimizer(n), '\n'). It does the same thing and is a little harder to read, but it does get rid of the use of print twice. If you think it is more readable as is though, feel free to ignore this

**Comment by walliuswilliam** [comment]
thanks, i think its easier for me to understand as is, but i appreciate the tip
