### ISSUE TITLE
math.exp instead of math.e

### ISSUE THREAD

**Issue by RavenHex1296** [walliuswilliam/machine-learning#9]
This is really small but had the input been longer using math.exp is usually easier to read and handle than math.e ** (num). You used (1+math.e**prediction) in you predict method for Logistic Regressor, which is fine but using math.exp would make it a tiny bit easier to read. Again, for this it doesn't really matter and is based on personal preference.

**Comment by walliuswilliam** [comment]
thanks, i changed it
